twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic: /teleop/cmd_vel
        timeout: 0.5
        priority: 20

      estop_zero:
        topic: /cmd_vel_estop
        timeout: 0.5
        priority: 255

    locks:
      emergency_stop:
        topic: /emergency_stop_lock
        timeout: 0.0
        priority: 100